### ISSUE TITLE
Make historydict dottable

### ISSUE THREAD

**Issue by ericdill** [Nikea/historydict#26]
Request by @ambarb

**Comment by danielballan** [comment]
I do not think we will do this. HistoryDict is a dict, not a namedtuple. If we made it dottable, we would have to reserve some names.

**Comment by ericdill** [comment]
> HistoryDict is a dict, not a namedtuple

`metadatastore.document.Document` is a subclass of `MutableMapping` just like `HistoryDict` is and we made `Document` dottable. Why can't we do the same thing to `HistoryDict`?
