### ISSUE TITLE
file writing with sqlite

### ISSUE THREAD

**Issue by jrmlhermitte** [Nikea/historydict#31]
Is there a way to keep sqlite from writing to file immediately.
Typical practice in an OS is to not `close()` a file until finished with it.

I'm wondering if there's possibility to remove this line [here](https://github.com/Nikea/historydict/blob/master/historydict.py#L158):
`self._conn.commit()`

Flagging this to revisit later.

The motivation here is that we have the following timings on out GPFS partitions:
(i.e. let the OS do its thing and buffer)
```
In [1]: #GPFS

In [2]: f= open("/nsls2/xf08id/User Data/foo.txt", "w");

In [3]: %timeit f.write("bar")
233 ns ± 13.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [4]: f.close()

As opposed to:
In [7]: #GPFS

In [8]: %timeit f= open("/nsls2/xf08id/User Data/foo.txt", "w"); f.write("bar"); f.close()
214 µs ± 64 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Who knows most about this? @danielballan ?
When I have the time I will revisit. Just flagging that I'd like to discuss this. thanks!

**Comment by danielballan** [comment]
I think our motivation was to ensure that everything gets synced even if IPython exits badly later, analogous to `f.flush()` for a file object.

**Comment by jrmlhermitte** [comment]
you're right. there really is no way around that.

In passing, I'm wondering if there's something a little simpler we can use, like [`zict`](http://zict.readthedocs.io/en/latest/):
```py
import pickle
import zlib

from zict import File, Func, LRU

a = File('myfile/', mode='a')
b = Func(zlib.compress, zlib.decompress, a)
c = Func(pickle.dumps, pickle.loads, b)
```

Would you be okay that I test this at ISS?

**Comment by jrmlhermitte** [comment]
we'd have to possibly ask to add `flush()` [here](https://github.com/dask/zict/blob/master/zict/file.py#L85).

My motivation here is that I'm worried that sqlite may be doing more than we need. From reading, it seems that `flush()` just flushes the data out of python into the OS. However, the OS may choose to keep buffering before writing which could help with our GPFS issues. Since the buffer is in the OS, it would be safe by then.

The only issue is that we'd have to hope `RE.md` doesn't accumulate too many keys. This is creating a separate file per element. Just some thoughts

**Comment by tacaswell** [comment]
We also should not be updating `RE.md` in a tight loop (it should be once per run (to increment the `scan_id` and then when ever the user explicitly pokes it).  If ISS is hitting this all the time, we should refactor their code to pass those keys through one of the more transient ways (either as kwargs to RE or via the `md` arg on the plans or via the kwargs on the `open_run` msg).

IPython uses sqlite for it's history (as does most web-browsers!) so I think that sqlite is a reasonable fit for what we are doing with it.

Are we sure that `_conn.commit()` is analogous to `close`?  My understand is that `commit` is finalizing the sql transaction and it is up to sqlite to translate that to disk writes however it wants (and it may be holding a file open under the hood).  We are being good about caching the `_conn` object

**Comment by jrmlhermitte** [comment]
I think so, from [here](https://docs.python.org/2/library/sqlite3.html):
```py
# Save (commit) the changes
conn.commit()

# We can also close the connection if we are done with it.
# Just be sure any changes have been committed or they will be lost.
```

I take this as saying "when commit is called, we can guarantee that any other connections to the database will receive the updates from commit". Since sqlite involves reading a file, then only way to ensure this is to `sync` in the OS, i.e. write to disk. (I take as an example of opening a file that I'm writing to with a text editor. If it's in the OS buffer but not yet `sync`ed I won't see those files, at least that's what I remember from C programming....)

**Comment by jrmlhermitte** [comment]
And `RE.md` is not hit in a tight loop. They have the problem once during intialization and then during the scans (when I guess `scan_nd` is updated).
You're right, we can probably change something like:
```py
RE.md['proposal'] = 132
RE.md['user'] = "joe"
...
```

to 

```
RE.update(dict(....))
```


It's not a big problem for them. I was mainly worried that sqlite may be too complex for what they need. I'm trying my best to find a solution to this GPFS slowness issue. But it seems like we'll have to push IT to find a better solution. (some machines suffer less latencies than others for example. we could consider upgrading the slow machines to similar specs of the fast ones)

**Comment by danielballan** [comment]
I think it is reasonable to give `zict` a try. I actually had the same thought during PyData NYC and could have sworn that I opened a GH issue at the time, but apparently not.

The main reason I think that's interesting is that if we decide we like `zict` at least as well, maybe we can adopt it as our standard in the name or reuse and stop maintaining `historydict`.

If it also happened to help with the performance issues for some accidental reason, then that doesn't hurt. However, given that IPython itself is writing to a sqlite file once per command executed, it seems likely we will have to solve the underlying issue anywhere, as a performant `RE.md` is little use if IPython itself is hampered.

**Comment by jrmlhermitte** [comment]
Just to summarize, `zict` as is may not be the best option, since it writes a file per key. @danielballan  has suggested that perhaps we move `historydict` into `zict`, and made an issue [here](https://github.com/dask/zict/issues/24).

The advantage of moving to `zict` is more users using (and testing it), and wider support from a larger community. @tacaswell  might have some thoughts about this?

I think the discussion will move there. Leaving open until it is resolved.

**Comment by danielballan** [comment]
Zict provides a range of storage options for mutable-mapping objects. Historydict adds an extra bit of interface to dict: the `.past` method. If we move Historydict in zict, I would expect that we would not move that feature, only the "sqlite-backed mutable mapping interface". We would also adopt zict's restriction that the dict keys must be strings.

I don't think our users will miss the `past` method; it was never as useful as we originally imagined it might be, and most don't even know about it. And the "keys are strings" restriction probably should have been there all along.

**Comment by jrmlhermitte** [comment]
any energy to try this out? (contributing to zict?)

**Comment by danielballan** [comment]
It's interesting but very low on the priority list, especially now....

**Comment by tacaswell** [comment]
I think this is adequately tracked by via the zict issue referenced above.
